# Generated by Django 4.2.1 on 2023-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[('M', '1'), ('F', '0')])),
                ('exang', models.IntegerField(choices=[('Yes', 1), ('No', 0)])),
                ('cp', models.IntegerField(choices=[('typical angina', '1'), ('atypical angina', '2'), ('non-anginal pain', '3'), ('asymptomatic', '4')])),
                ('trtbps', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fbs', models.IntegerField(choices=[('Yes', '1'), ('No', '0')])),
                ('rest_ecg', models.IntegerField(choices=[('normal', '0'), ('having ST-T wave abnormality', '1'), ('showing probable or definite left ventricular hypertrophy', '2')])),
            ],
        ),
    ]
