# Generated by Django 4.2.1 on 2023-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='target',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='chol',
            field=models.IntegerField(help_text='cholestoral in mg/dl fetched via BMI sensor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cp',
            field=models.CharField(choices=[(1, 'typical angina'), (2, 'atypical angina'), (3, 'non-anginal pain'), (4, 'asymptomatic')], help_text='Chest Pain type', max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='exang',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], help_text='exercise induced angina', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fbs',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], help_text='fasting blood sugar > 120 mg/dl', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rest_ecg',
            field=models.CharField(choices=[(0, 'normal'), (1, 'having ST-T wave abnormality'), (2, 'probable or definite left ventricular hypertrophy')], help_text='resting electrocardiographic results', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[(1, 'M'), (0, 'F')], max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='trtbps',
            field=models.IntegerField(help_text='resting blood pressure (in mm Hg)'),
        ),
    ]
