# Generated by Django 4.2.1 on 2023-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_patient_target_alter_patient_chol_alter_patient_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='target',
            field=models.CharField(blank=True, choices=[(1, 'Yes'), (0, 'No')], max_length=2, null=True),
        ),
    ]
