# Generated by Django 4.2.1 on 2023-06-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_patient_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='caa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='oldpeak',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='slp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='thall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
