# Generated by Django 4.2.1 on 2023-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_patient_thalachh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cp',
            field=models.IntegerField(choices=[(1, 'typical angina'), (2, 'atypical angina'), (3, 'non-anginal pain'), (4, 'asymptomatic')], help_text='Chest Pain type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='exang',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], help_text='exercise induced angina'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fbs',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], help_text='fasting blood sugar > 120 mg/dl'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rest_ecg',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'having ST-T wave abnormality'), (2, 'probable or definite left ventricular hypertrophy')], help_text='resting electrocardiographic results'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(1, 'M'), (0, 'F')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='target',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
    ]
